### PR TITLE
003, 007 Changes

### PR DESCRIPTION
**Pull request by kefo**
Hey @wafschneider .

The 001-007 document is complete so far as I can tell.  Everything that needed to be done should be part of this pull request.  It uses the "new method" of creating a XML representation of a list where a new list needed to be added, but if all I had to do was add new URIs or alter labels, I just made the change where I needed to in which ever pattern was being used.

One thing I did, in consultation with @jodiw01, was to output dimensions if there was no 300/c.  The instruction was to "Ignore" but that set up a situation where it might be overly lossy since we cannot guarantee everything has a 300/c.

I removed all bflc:target references, which shouldn't be controversial, but I'm tagging @jodiw01 to tell me I've gone too far.

All tests pass.  Let me know if you want to see any changes.  I've merged master in and didn't encounter an issue.

### CODE REVIEW

**Comment by wafschneider** [comment]
Thanks, @kefo! I'll review as soon as possible and get this merge. Much appreciated.

**Comment by wafschneider** [comment]
Oh, never mind on dimensions, just reviewed your earlier comment :-) -- so just waiting on feedback on the 003.

**Comment by wafschneider** [comment]
@kirkhess -- is your comment in reference to the 003 conversion? The spec is to place the value in the 003 as the literal object of an `rdf:value` predicate. My question was whether the class of the object of the bf:source predicate (whether blank node or not) should be `bf:Agent`, `bf:Source`, or both.

**Comment by kirkhess** [comment]
@wafschneider I typed up that comment looking at 5bd2ad7. 

I'm not sure I see the utility of bf:Source in this case - it's clearly a bf:Agent so I would suggest only bf:Agent.  "Resource from which value or label came or was derived." is a very vague description when we know these codes are for an organization.

**Pull request merged**
